import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container:{
        flex:1,
        alignItems:"center",
        justifyContent:"center"
    },inputResposta:{
        width:306,
        height:48,
        backgroundColor:"#F6F6F6",
        borderColor:"black",
        borderWidth:1,
        borderRadius:15,
        textAlign:"center",
        fontSize:24
    },textoInput:{
        color:"#333333",
        fontSize:18,
    },input1:{
        marginBottom:60
    },inputs:{
        height:"80%",
        justifyContent:"center"
    },botao:{
        width:176,
        height:48,
        backgroundColor:"#01633D",
        justifyContent:"center",
        alignItems:"center",
        borderRadius:12
    },textoBotao:{
        color:"white",
        fontWeight:"bold",
        fontSize:24
    },botoes:{
        flexDirection:"row",
        width:"100%",
        gap:4,
        justifyContent:"center"
    }
})